#将使用eureka注册的服务逻辑名称
spring:
  application:
    profiles: dev # 开发环境 
    name: idc-flight-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.89.171:33306/saedb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
idc-sdk:
  idc-response.enabled: true


server:
  port: 5001
#eureka服务位置
eureka:
#  instanc中的配置是让该服务使用IP注册到注册中心，而不是hostname
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true
feign: 
  hystrix: 
    enabled: true 
